image: Visual Studio 2017

cache:
- c:\Tools\vcpkg\installed\

build_script:
- cmd: >-
    vcpkg install boost:x64-windows

    mkdir build

    cd build

    cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake  .. -G "Visual Studio 15"
